#!/bin/sh
# Copyright (C) 2026 The MegaMek Team. All Rights Reserved.
#
# This file is part of MegaMek Launcher.
#
# MegaMek Launcher is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License (GPL),
# version 3 or (at your option) any later version,
# as published by the Free Software Foundation.
#
# MegaMek Launcher is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
#
# A copy of the GPL should have been included with this project;
# if not, see <https://www.gnu.org/licenses/>.
#
# NOTICE: The MegaMek organization is a non-profit group of volunteers
# creating free software for the BattleTech community.
#
# MechWarrior, BattleMech, `Mech and AeroTech are registered trademarks
# of The Topps Company, Inc. All Rights Reserved.
#
# Catalyst Game Labs and the Catalyst Game Labs logo are trademarks of
# InMediaRes Productions, LLC.
#
# MechWarrior Copyright Microsoft Corporation. MegaMek was created under
# Microsoft's "Game Content Usage Rules"
# <https://www.xbox.com/en-US/developers/rules> and it is not endorsed by or
# affiliated with Microsoft.
#

set -eu

SCRIPT_DIR=${0%/*}
[ "$SCRIPT_DIR" != "$0" ] || SCRIPT_DIR=.
[ -n "$SCRIPT_DIR" ] || SCRIPT_DIR=/
APP_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR" && pwd -P)
SHARED_LIB="$APP_ROOT/MegaMek Launcher.app/Contents/app/lib"

if [ -x "$APP_ROOT/runtime/bin/java" ]; then
    unset JDK_JAVA_OPTIONS JAVA_TOOL_OPTIONS _JAVA_OPTIONS
    exec "$APP_ROOT/runtime/bin/java" -cp "$SHARED_LIB/*" org.megamek.launcher.DesktopLauncher "$@"
fi

find_java() {
    if [ -n "${JAVA_HOME:-}" ]; then
        if [ ! -x "${JAVA_HOME}/bin/java" ]; then
            printf '%s\n' "MegaMek Launcher: JAVA_HOME does not contain an executable bin/java." >&2
            return 1
        fi
        printf '%s\n' "${JAVA_HOME}/bin/java"
        return 0
    fi
    command -v java 2>/dev/null || return 1
}

JAVA_COMMAND=$(find_java) || {
    printf '%s\n' "MegaMek Launcher requires an external Java 21 or newer runtime." >&2
    exit 2
}

JAVA_FEATURE=$(
    "$JAVA_COMMAND" -XshowSettings:properties -version 2>&1 |
        sed -n 's/^[[:space:]]*java\.version = \([0-9][0-9]*\).*/\1/p' |
        sed -n '1p'
)
case "$JAVA_FEATURE" in
    ''|*[!0-9]*)
        printf '%s\n' "MegaMek Launcher could not determine the selected Java version." >&2
        exit 2
        ;;
esac
if [ "$JAVA_FEATURE" -lt 21 ]; then
    printf '%s\n' "MegaMek Launcher requires Java 21 or newer; found Java ${JAVA_FEATURE}." >&2
    exit 2
fi

unset JDK_JAVA_OPTIONS JAVA_TOOL_OPTIONS _JAVA_OPTIONS
exec "$JAVA_COMMAND" -cp "$SHARED_LIB/*" org.megamek.launcher.DesktopLauncher "$@"
